#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -f "/etc/network.conf" ]; then
    . /etc/network.conf
fi

WWMASTER=`sed -e '/ wwmaster=/!d;s/.*wwmaster=\([^ ]*\).*/\1/' /proc/cmdline`
export WWMASTER
WWPORT=`sed -e '/ wwport=/!d;s/.*wwport=\([^ ]*\).*/\1/' /proc/cmdline`
export WWPORT

if [ -z "$WWPORT" ]; then
    WWPORT=9870
fi

if [ -z "$WWMASTER" ]; then
    if [ -n "$DHCP_SERVER" ]; then
        WWMASTER=$DHCP_SERVER
    else
        echo "ERROR: Could not identify master node!"
        exit 1
    fi
fi

