#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions


TMPFILE=`mktemp`

while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
        if wget -q -O $TMPFILE "http://$master:$WWPORT/file?hwaddr=$HWADDR" 2>/dev/null; then
            cat $TMPFILE | while read id name uid gid mode path; do
                if wget -q -O - "http://$master:$WWPORT/file?fileid=$id" > $NEWROOT/$path; then
                    chown $uid $NEWROOT/$path
                    chgrp $gid $NEWROOT/$path
                    chmod $mode $NEWROOT/$path
                else
                    echo "ERROR: Could not download $name"
                    exit 1
                fi
            done
            exit 0
        fi
    done
    echo -n "." 1>&2
    throttled_sleep
done

