#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions


TMPFILE=`mktemp`

while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
        if wget -q -O $TMPFILE "http://$master/WW/file?hwaddr=$HWADDR" 2>/dev/null; then
            cat $TMPFILE | while read id name uid gid mode sum1 path; do
                if [ -f $path ]; then
                    sum2=`md5sum $path | cut -d ' ' -f 1`
                    if [ "$sum1" == "$sum2" ]; then
                        continue
                    fi
                fi
                basedir=`dirname $path`
                if [ ! -d "$NEWROOT/$basedir" ]; then
                    mkdir -p $NEWROOT/$basedir
                fi
                if wget -q -O - "http://$master/WW/file?hwaddr=$HWADDR&fileid=$id" > $NEWROOT/$path.$sum1; then
                    sum2=`md5sum $NEWROOT/$path.$sum1 | cut -d ' ' -f 1`
                    if [ "$sum1" == "$sum2" ]; then
                        chown $uid $NEWROOT/$path.$sum1
                        chgrp $gid $NEWROOT/$path.$sum1
                        chmod $mode $NEWROOT/$path.$sum1
                        mv $NEWROOT/$path.$sum1 $NEWROOT/$path
                    else
                        rm -f $NEWROOT/$path.$sum1
                    fi
                else
                    echo "ERROR: Could not download $name"
                    exit 2
                fi
            done
            rm -f $TMPFILE
            exit 0
        fi
    done
    echo -n "." 1>&2
    throttled_sleep
done

