#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -f /warewulf/transports/http/functions ]; then
    . /warewulf/transports/http/functions
elif [ -f ./functions ]; then
    # For debugging
    . ./functions
else
    exit
fi

if [ -n "$RANDOM" -a ! -f "/init" ]; then
    SLEEPTIME=`expr $RANDOM % 30`
#    sleep $SLEEPTIME
fi

TIMESTAMP_FILE="$NEWROOT/tmp/.wwgetfiles_timestamp"
if [ ! -d $NEWROOT/tmp/ ]; then
    mkdir $NEWROOT/tmp/
fi

if [ -f "$TIMESTAMP_FILE" ]; then
    TIMESTAMP=`cat $TIMESTAMP_FILE`
fi

while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
        TMPFILE=`mktemp`
        if wget -q -O $TMPFILE "http://$master/WW/file?hwaddr=$HWADDR&timestamp=$TIMESTAMP" 2>/dev/null; then
            cat $TMPFILE | while read id name uid gid mode timestamp path; do
                basedir=`dirname $path`
                if [ ! -d "$NEWROOT/$basedir" ]; then
                    mkdir -p $NEWROOT/$basedir
                fi
                if wget -q -O $NEWROOT/$path.ww "http://$master/WW/file?hwaddr=$HWADDR&fileid=$id"; then
                    chown $uid $NEWROOT/$path.ww
                    chgrp $gid $NEWROOT/$path.ww
                    chmod $mode $NEWROOT/$path.ww
                    mv $NEWROOT/$path.ww $NEWROOT/$path
                    echo $timestamp > $TIMESTAMP_FILE
                else
                    echo "ERROR: Could not download $name"
                    exit 2
                fi
            done
            rm -f $TMPFILE
            exit 0
        fi
    done
    echo -n "." 1>&2
    throttled_sleep
done

