#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions

MESSAGE=`echo $1 | sed -e 's@ @+@g'`

for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
    echo "<6>$WWNAME wwbootstrap: $MESSAGE" | nc -w 0 -u $master 514 2>/dev/null
done
