#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions

MESSAGE=`echo $1 | sed -e 's@ @+@g'`

for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
    wget -q -O /dev/null "http://$master/WW/logger?hwaddr=$HWADDR&status=$MESSAGE"
done

