#!/bin/sh
#
# Copyright (c) 2003-2010, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# The GNU GPL Document can be found at:
# http://www.gnu.org/copyleft/gpl.html
#

KVERSION=`uname -r`

if [ ! -f /lib/modules/$KVERSION/modules.pcimap ]; then
    echo "PCI map for this kernel is not available!"
    exit 1
fi

if [ ! -d /sys/bus/pci/devices ]; then
    echo "The SYSFS file system is not available!"
    exit 1
fi


for pci in /sys/bus/pci/devices/*; do
    VENDOR_1=`cat $pci/vendor`
    DEVICE_1=`cat $pci/device`
    VENDOR=`printf "0x%08x\n" $VENDOR_1`
    DEVICE=`printf "0x%08x\n" $DEVICE_1`
    grep "$VENDOR $DEVICE" /lib/modules/$KVERSION/modules.pcimap | awk '{print $1}'
done
