#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

KVERSION=`uname -r`

if [ ! -f /lib/modules/$KVERSION/modules.pcimap ]; then
    echo "PCI map for this kernel is not available!"
    exit 1
fi

if [ ! -d /sys/bus/pci/devices ]; then
    echo "The SYSFS file system is not available!"
    exit 1
fi


for pci in /sys/bus/pci/devices/*; do
    VENDOR_1=`cat $pci/vendor`
    DEVICE_1=`cat $pci/device`
    VENDOR=`printf "0x%08x\n" $VENDOR_1`
    DEVICE=`printf "0x%08x\n" $DEVICE_1`
    grep "$VENDOR $DEVICE" /lib/modules/$KVERSION/modules.pcimap | awk '{print $1}'
done
