#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#



if test -n "$ip"; then
   ifconfig $interface $ip netmask $subnet
fi
if test -n "$dns"; then
   > /etc/resolv.conf
   for i in "$dns"; do
      echo "nameserver $i" >> /etc/resolv.conf
   done
fi
if test -n "$router"; then
   route add default gw $router
fi
if test -n "$hostname"; then
    hostname $hostname
fi
