#!/bin/sh




WWMASTER=`sed -e '/ wwmaster=/!d;s/.*wwmaster=\([^ ]*\).*/\1/' /proc/cmdline`
export WWMASTER

ETH_IP=`sed -e '/ eth_ip=/!d;s/.*eth_ip=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_IP

ETH_NETMASK=`sed -e '/ eth_netmask=/!d;s/.*eth_netmask=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_NETMASK

ETH_GW=`sed -e '/ eth_gw=/!d;s/.*eth_gw=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_GW

ETH_DNS=`sed -e '/ eth_dns=/!d;s/.*eth_dns=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_DNS

ETH_DEV=`sed -e '/ eth_dev=/!d;s/.*eth_dev=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_DEV

ETH_MTU=`sed -e '/ eth_mtu=/!d;s/.*eth_mtu=\([^ ]*\).*/\1/' /proc/cmdline`
export ETH_MTU





GRAY="\\033[1;30m"
RED="\\033[1;31m"
GREEN="\\033[1;32m"
YELLOW="\\033[1;33m"
BLUE="\\033[1;34m"
PINK="\\033[1;35m"
CYAN="\\033[1;36m"
WHITE="\\033[1;37m"
NORMAL="\\033[0;39m"


msg_blue() {
    echo -ne "$BLUE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_red() {
    echo -ne "$RED"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_green() {
    echo -ne "$GREEN"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_white() {
    echo -ne "$WHITE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_gray() {
    echo -ne "$GRAY"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_blue() {
    echo -ne "$BLUE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg() {
    msg_white $@
}

run() {
    if [ -n "$1" ]; then
        echo -ne "$GRAY"
        $@ >/dev/null
        RETVAL=$?
        echo -ne "$NORMAL"
    fi
    return $RETVAL
}
