#!/bin/sh
#
# Copyright (c) 2003-2010, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# The GNU GPL Document can be found at:
# http://www.gnu.org/copyleft/gpl.html
#


WWDEBUG=0

WWDEBUG=`sed -e '/ wwdebug=/!d;s/.*wwdebug=\([^ ]*\).*/\1/' /proc/cmdline`
export WWDEBUG

WWNODE=`sed -e '/ wwnode=/!d;s/.*wwnode=\([^ ]*\).*/\1/' /proc/cmdline`
export WWNODE

WWMASTER=`sed -e '/ wwmaster=/!d;s/.*wwmaster=\([^ ]*\).*/\1/' /proc/cmdline`
export WWMASTER

WWPORT=`sed -e '/ wwport=/!d;s/.*wwport=\([^ ]*\).*/\1/' /proc/cmdline`
export WWPORT

WWCGI=`sed -e '/ wwcgi=/!d;s/.*wwcgi=\([^ ]*\).*/\1/' /proc/cmdline`
export WWCGI

WWIP=`sed -e '/ wwip=/!d;s/.*wwip=\([^ ]*\).*/\1/' /proc/cmdline`
export WWIP

WWNETMASK=`sed -e '/ wwnetmask=/!d;s/.*wwnetmask=\([^ ]*\).*/\1/' /proc/cmdline`
export WWNETMASK

WWGW=`sed -e '/ wwgw=/!d;s/.*wwgw=\([^ ]*\).*/\1/' /proc/cmdline`
export WWGW

WWDNS=`sed -e '/ wwdns=/!d;s/.*wwdns=\([^ ]*\).*/\1/' /proc/cmdline`
export WWDNS

WWDEV=`sed -e '/ wwdev=/!d;s/.*wwdev=\([^ ]*\).*/\1/' /proc/cmdline`
export WWDEV

WWMTU=`sed -e '/ wwmtu=/!d;s/.*wwmtu=\([^ ]*\).*/\1/' /proc/cmdline`
export WWMTU

if [ -z "$WWPORT" ]; then
    WWPORT=9870
fi

if [ -z "$WWCGI" -a -n "$WWMASTER" ]; then
   WWCGI="http://$WWMASTER:$WWPORT/"
fi


GRAY="\\033[1;30m"
RED="\\033[1;31m"
GREEN="\\033[1;32m"
YELLOW="\\033[1;33m"
BLUE="\\033[1;34m"
PINK="\\033[1;35m"
CYAN="\\033[1;36m"
WHITE="\\033[1;37m"
NORMAL="\\033[0;39m"


msg_blue() {
    echo -ne "$BLUE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_red() {
    echo -ne "$RED"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_green() {
    echo -ne "$GREEN"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_white() {
    echo -ne "$WHITE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_gray() {
    echo -ne "$GRAY"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg_blue() {
    echo -ne "$BLUE"
    echo -ne "$1"
    echo -ne "$NORMAL"
}

msg() {
    msg_white $@
}

run() {
    if [ -n "$1" ]; then
        if [ $WWDEBUG -eq 0 ]; then
            $@ >/dev/null 2>&1
            RETVAL=$?
        elif [ $WWDEBUG -eq 1 ]; then
            echo -ne "$GRAY"
            $@ >/dev/null
            RETVAL=$?
            echo -ne "$NORMAL"
        elif [ $WWDEBUG -gt 1 ]; then
            echo -ne "$GRAY"
            $@
            RETVAL=$?
            echo -ne "$NORMAL"
        fi
    fi
    return $RETVAL
}




if [ $WWDEBUG -gt 3 ]; then
    set -x
fi

