#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


# This script relies on the Warewulf init scrip to drop the file /tmp/wwdev
# which must contain the network device name of the device used to
# communicate to the WW master.

NETDEV=`cat /tmp/wwdev`
if [ -f "/sys/class/net/$NETDEV/address" ]; then
    cat /sys/class/net/$NETDEV/address
fi

