#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


WWMETHOD=`sed -e '/ wwmethod=/!d;s/.*wwmethod=\([^ ]*\).*/\1/' /proc/cmdline`
export WWMETHOD

if [ -z "$WWMETHOD" ]; then
    WWMETHOD="http"
fi

PROG=$0

if [ -x "$PROG.$WWMETHOD" ]; then
    exec $PROG.$WWMETHOD $@
else
    echo "WARNING: Method $WWMETHOD is not supported!" 1>&2
fi
