#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


. /etc/functions


if [ -d "/warewulf/provision/" ]; then
    for i in `find /warewulf/provision/ -type f | sort -n`; do
        if [ -x "$i" -a -f "$i" ]; then
            NAME=`basename $i | sed -e 's/^[0-9]*-\(.*\)/\1/'`
            msg_white " * $NAME "
            sh $i
            RETVAL=$?
            if [ $RETVAL -eq 0 ]; then
                wwsuccess
            elif [ $RETVAL -gt 1 ]; then
                wwfailure
                wwreboot
            else
                wwfailure
            fi
        fi
    done
fi

