#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


TRANSPORT=`sed -e '/ wwtransport=/!d;s/.*wwtransport=\([^ ]*\).*/\1/' /proc/cmdline`
export TRANSPORT


if [ -z "$TRANSPORT" ]; then
    TRANSPORT="http"
fi

PROG=`basename $0`

if [ -f "/warewulf/transports/register.$TRANSPORT" ]; then
    if [ -x "/warewulf/transports/$PROG.$TRANSPORT" ]; then
        exec /warewulf/transports/$PROG.$TRANSPORT $@
    elif [ -f "/warewulf/transports/$PROG.$TRANSPORT" ]; then
        echo "WARNING: /warewulf/transports/$PROG.$TRANSPORT is not executable"
    fi
else
    echo "WARNING: Transport method $TRANSPORT is not supported!" 1>&2
fi
