#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


TRANSPORT=`sed -e '/ wwtransport=/!d;s/.*wwtransport=\([^ ]*\).*/\1/' /proc/cmdline`
export TRANSPORT


if [ -z "$TRANSPORT" ]; then
    TRANSPORT="http"
fi

PROG=$0

if [ -x "$PROG.$TRANSPORT" ]; then
    exec $PROG.$TRANSPORT $@
else
    echo "WARNING: Transport method $TRANSPORT is not supported!" 1>&2
fi
