#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


cd $NEWROOT

if ! wwgetvnfs | gunzip 2>/dev/null | cpio -id --quiet 2>/dev/null; then
    exit 255
fi


