#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -z "$WWDISKLAYOUT" ]; then
    WWDISKLAYOUT="none:/:tmpfs:512"
#    WWDISKLAYOUT="sda1:/:ext2:768,sda2:none:swap:128,sda3:/scratch:ext2:"
fi

if [ "x$WWDISKPARTITION" == "xyes" ]; then
    WWDISKFORMAT="yes"

    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
        if [ "x$DISK" != "xnone" ]; then
            echo $DISK
        fi
    done | sort | uniq | while read dev; do
        dd if=/dev/zero of=/dev/$dev count=1 bs=512 >/dev/null 2>&1
    done

    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
        FILESYSTEM=`echo $string | awk -F : '{print $3}'`
        SIZE=`echo $string | awk -F : '{print $4}'`
        PARTNUM=`echo $DEV | sed -e 's@...\([0-9]\)@\1@'`
        DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
        if [ ${SIZE:-0} -gt 0 ]; then
            SIZE="+${SIZE}M";
        fi

        case $FILESYSTEM in
            ext2)
#                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nw\n"
                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
            ;;
            swap)
#                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nt\n$PARTNUM\n82\nw\n"
                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nt\n$PARTNUM\n82\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
            ;;
        esac
    done

fi

if [ "x$WWDISKFORMAT" == "xyes" ]; then
    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
        FILESYSTEM=`echo $string | awk -F : '{print $3}'`

        case $FILESYSTEM in
            ext2)
                /sbin/mkfs.$FILESYSTEM /dev/$DEV >/dev/null
            ;;
            swap)
                /sbin/mkswap /dev/$DEV >/dev/null
            ;;
            tmpfs)
                /bin/true
            ;;
            *)
                echo "UNKNOWN FILESYSTEM: '$FILESYSTEM'"
            ;;
        esac
    done
fi



mkdir -p $NEWROOT
> /tmp/filesystems
> /tmp/fstab

for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
    DEV=`echo $string | awk -F : '{print $1}'`
    MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
    FILESYSTEM=`echo $string | awk -F : '{print $3}'`
    SIZE=`echo $string | awk -F : '{print $4}'`
    DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`

    if [ "x$MOUNTPOINT" == "x/" -a "x$FILESYSTEM" != "xtmpfs" ]; then
        echo "$DEV $DISK" > /tmp/stateful-root
    fi

    case $FILESYSTEM in
        ext2)
            echo "${MOUNTPOINT:-none} $DEV $FILESYSTEM ${SIZE:-0}" >> /tmp/filesystems
        ;;
        swap)
            echo "none $DEV $FILESYSTEM" >> /tmp/filesystems
        ;;
        tmpfs)
            echo "${MOUNTPOINT:-none} none $FILESYSTEM ${SIZE:-0}" >> /tmp/filesystems
        ;;
    esac
done

# GMK: Still must figure out a way of dealing with the tmpfs size!

sort /tmp/filesystems | while read MOUNTPOINT DEV FILESYSTEM SIZE; do
    if [ "x$DEV" == "xnone" ]; then
        DEV=$FILESYSTEM
    else
        DEV="/dev/$DEV"
    fi
    if [ "x$MOUNTPOINT" == "xnone" ]; then
        echo "$DEV $MOUNTPOINT $FILESYSTEM defaults 0 0" >> /tmp/fstab
    else
        echo "$DEV $MOUNTPOINT $FILESYSTEM defaults 1 2" >> /tmp/fstab
    fi
    if [ -n "$MOUNTPOINT" -a "x$MOUNTPOINT" != "xnone" ]; then
        mkdir -p $NEWROOT/$MOUNTPOINT
        if [ $FILESYSTEM == "tmpfs" -a ${SIZE:-0} -gt 0 ]; then
            OPTS="-o size=${SIZE}M "
        else
            OPTS=""
        fi
        if mount -t $FILESYSTEM $OPTS $DEV $NEWROOT/$MOUNTPOINT; then
            test -d $NEWROOT/etc || mkdir -p $NEWROOT/etc
            echo "$DEV $MOUNTPOINT $FILESYSTEM rw 1 2" >> $NEWROOT/etc/mtab
        else
            echo
            echo "ABORT: There was an error mounting the file system!"
            exit 255
        fi
    fi
done

cat <<EOF >> /tmp/fstab
none /dev/shm tmpfs defaults 0 0
devpts /dev/pts devpts gid=5,mode=620 0 0
sysfs /sys sysfs defaults 0 0
proc /proc proc defaults 0 0
EOF
