#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

if [ -z "$WWMOUNT" ]; then
    WWMOUNT="dev=none:mountpoint=/:type=tmpfs:options=size=512M"
fi

#WWPART="sda"
#WWFORMAT="sda1 sda2 sda3"
#WWMOUNT="dev=sda1:mountpoint=/:type=ext2:size=768 dev=sda2:type=swap:size=1024 dev=sda3:mountpoint=/foo:type=ext2:size=10240"

TMPDIR=`mktemp -d`
mkdir $TMPDIR/wwfs
> /tmp/fstab
> /tmp/mptab
> /tmp/mtab


for FSYS in `echo $WWMOUNT | sed 's/,/ /g'` ; do
    ( 
        TMPFILE=`mktemp`
        for SETVAR in `echo $FSYS | sed 's/:/ /g'` ; do
            VAR=`echo $SETVAR | cut -d= -f1 | tr '[a-z]' '[A-Z]'`
            VAL=`echo $SETVAR | cut -d= -f2-`
            eval "WWFS_$VAR=$VAL"
            echo "WWFS_$VAR=$VAL" >> $TMPFILE
            echo "export WWFS_$VAR" >> $TMPFILE
        done
        if [ -n "$WWFS_DEV" ]; then
            DISK=`echo $WWFS_DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
            mv $TMPFILE $TMPDIR/wwfs/$WWFS_DEV
            if [ -n "$DISK" ]; then
                echo "$WWFS_DEV" >> $TMPDIR/$DISK
            fi
            if [ -n "$WWFS_DEV" -o "$WWFS_DEV" == "none" ]; then
                DEV="none"
            else
                DEV="/dev/$WWFS_DEV"
            fi
            if [ -n "$WWFS_TYPE" ]; then
                if [ "x$WWFS_MOUNTPOINT" == "x/" ]; then
                    echo "$WWFS_MOUNTPOINT $DEV $WWFS_TYPE ${WWFS_OPTIONS:-defaults} 0 0" >> /tmp/mptab
                else
                    echo "${WWFS_MOUNTPOINT:-none} $DEV $WWFS_TYPE ${WWFS_OPTIONS:-defaults} 1 2" >> /tmp/mptab
                fi
            fi
        else
            rm -f $TMPFILE
        fi
    )
done

for DEV in `echo $WWPART | sed 's/,/ /g'` ; do
    (
        if [ -f "$TMPDIR/$DEV" ]; then
            cat $TMPDIR/$DEV | while read part; do
                if [ -f "$TMPDIR/wwfs/$part" ]; then
                    . $TMPDIR/wwfs/$part
                    if [ -n "$WWFS_DEV" ]; then
                        PARTNUM=`echo $WWFS_DEV | sed -e 's@...\([0-9]\)@\1@'`
                        DISK=`echo $WWFS_DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
                        if [ -n "$WWFS_SIZE" ]; then
                            echo "PARTITIONING: $DISK"
                            case $WWFS_TYPE in
                                swap)
                                    echo -ne "n\np\n$PARTNUM\n$WWFS_START\n$WWFS_SIZE\nt\n$PARTNUM\n82\nw\n"
#                                    echo -ne "n\np\n$PARTNUM\n\n$SIZE\nt\n$PARTNUM\n82\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
                                ;;
                                *)
                                    echo -ne "n\np\n$PARTNUM\n$WWFS_START\n$WWFS_SIZE\nw\n"
#                                    echo -ne "n\np\n$PARTNUM\n\n$SIZE\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
                                ;;
                            esac
                        fi
                    fi
                fi
            done
        fi
    )
done

for DEV in `echo $WWFORMAT | sed 's/,/ /g'` ; do
    (
        if [ -f "$TMPDIR/wwfs/$DEV" ]; then
            . $TMPDIR/wwfs/$DEV
            case $WWFS_TYPE in
                swap)
                    echo /sbin/mkswap /dev/$WWFS_DEV
                ;;
                ext2)
                    echo /sbin/mkfs.ext2 /dev/$WWFS_DEV
                ;;
            esac
        fi
    )
done


sort /tmp/mptab | while read dev mp type opts freq passno; do
    echo "$dev $mp $type $opts $freq $passno" >> /tmp/fstab
    if echo "mount -o $opts -t $type $dev $NEWROOT/$mp"; then
        echo "$dev $mp $type $opts $freq $passno" >> /tmp/mtab
    fi
done

cat <<EOF >> /tmp/fstab
none /dev/shm tmpfs defaults 0 0
devpts /dev/pts devpts gid=5,mode=620 0 0
sysfs /sys sysfs defaults 0 0
proc /proc proc defaults 0 0
EOF

rm -rf $TMPDIR
exit;

if [ "x$WWDISKPARTITION" == "xyes" ]; then
    WWDISKFORMAT="yes"

    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
        if [ "x$DISK" != "xnone" ]; then
            echo $DISK
        fi
    done | sort | uniq | while read dev; do
        dd if=/dev/zero of=/dev/$dev count=1 bs=512 >/dev/null 2>&1
    done

    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
        FILESYSTEM=`echo $string | awk -F : '{print $3}'`
        SIZE=`echo $string | awk -F : '{print $4}'`
        PARTNUM=`echo $DEV | sed -e 's@...\([0-9]\)@\1@'`
        DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`
        if [ ${SIZE:-0} -gt 0 ]; then
            SIZE="+${SIZE}M";
        fi

        case $FILESYSTEM in
            ext2)
#                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nw\n"
                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
            ;;
            swap)
#                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nt\n$PARTNUM\n82\nw\n"
                echo -ne "n\np\n$PARTNUM\n\n$SIZE\nt\n$PARTNUM\n82\nw\n" | /sbin/fdisk /dev/$DISK > /dev/null || exit 255
            ;;
        esac
    done

fi

if [ "x$WWDISKFORMAT" == "xyes" ]; then
    for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
        DEV=`echo $string | awk -F : '{print $1}'`
        MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
        FILESYSTEM=`echo $string | awk -F : '{print $3}'`

        case $FILESYSTEM in
            ext2)
                /sbin/mkfs.$FILESYSTEM /dev/$DEV >/dev/null
            ;;
            swap)
                /sbin/mkswap /dev/$DEV >/dev/null
            ;;
            tmpfs)
                /bin/true
            ;;
            *)
                echo "UNKNOWN FILESYSTEM: '$FILESYSTEM'"
            ;;
        esac
    done
fi



mkdir -p $NEWROOT
> /tmp/filesystems
> /tmp/fstab

for string in `echo $WWDISKLAYOUT | sed -e 's@,@ @g'`; do
    DEV=`echo $string | awk -F : '{print $1}'`
    MOUNTPOINT=`echo $string | awk -F : '{print $2}'`
    FILESYSTEM=`echo $string | awk -F : '{print $3}'`
    SIZE=`echo $string | awk -F : '{print $4}'`
    DISK=`echo $DEV | sed -e 's@\([a-z]*\)[0-9]@\1@'`

    if [ "x$MOUNTPOINT" == "x/" -a "x$FILESYSTEM" != "xtmpfs" ]; then
        echo "$DEV $DISK" > /tmp/stateful-root
    fi

    case $FILESYSTEM in
        ext2)
            echo "${MOUNTPOINT:-none} $DEV $FILESYSTEM ${SIZE:-0}" >> /tmp/filesystems
        ;;
        swap)
            echo "none $DEV $FILESYSTEM" >> /tmp/filesystems
        ;;
        tmpfs)
            echo "${MOUNTPOINT:-none} none $FILESYSTEM ${SIZE:-0}" >> /tmp/filesystems
        ;;
    esac
done

# GMK: Still must figure out a way of dealing with the tmpfs size!

sort /tmp/filesystems | while read MOUNTPOINT DEV FILESYSTEM SIZE; do
    if [ "x$DEV" == "xnone" ]; then
        DEV=$FILESYSTEM
    else
        DEV="/dev/$DEV"
    fi
    if [ "x$MOUNTPOINT" == "xnone" ]; then
        echo "$DEV $MOUNTPOINT $FILESYSTEM defaults 0 0" >> /tmp/fstab
    else
        echo "$DEV $MOUNTPOINT $FILESYSTEM defaults 1 2" >> /tmp/fstab
    fi
    if [ -n "$MOUNTPOINT" -a "x$MOUNTPOINT" != "xnone" ]; then
        mkdir -p $NEWROOT/$MOUNTPOINT
        if [ $FILESYSTEM == "tmpfs" -a ${SIZE:-0} -gt 0 ]; then
            OPTS="-o size=${SIZE}M "
        else
            OPTS=""
        fi
        if mount -t $FILESYSTEM $OPTS $DEV $NEWROOT/$MOUNTPOINT; then
            test -d $NEWROOT/etc || mkdir -p $NEWROOT/etc
            echo "$DEV $MOUNTPOINT $FILESYSTEM rw 1 2" >> $NEWROOT/etc/mtab
        else
            echo
            echo "ABORT: There was an error mounting the file system!"
            exit 255
        fi
    fi
done

cat <<EOF >> /tmp/fstab
none /dev/shm tmpfs defaults 0 0
devpts /dev/pts devpts gid=5,mode=620 0 0
sysfs /sys sysfs defaults 0 0
proc /proc proc defaults 0 0
EOF
