#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


> $NEWROOT/etc/mtab

# Sigh... setting permission with mkdir will only work if the directory
#  doesn't already exist. So... 
if [ ! -d $NEWROOT/dev/shm -o ! -k $NEWROOT/dev/shm ]; then
    mkdir -p $NEWROOT/dev/shm
    chmod 1777 $NEWROOT/dev/shm
fi

chroot $NEWROOT /bin/mount -t tmpfs none /dev/shm;

sort -r /tmp/mptab | while read mp dev type perms opts; do
    if [ "x$mp" == "x/" ]; then
        echo "$dev $mp $type $opts 0 0" > $NEWROOT/etc/mtab
        mount -o remount,ro $NEWROOT/
    else
        if ! umount $NEWROOT/$mp; then
            mount -o remount,ro $NEWROOT/$mp
        fi
    fi
done

# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
