#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


> $NEWROOT/etc/mtab

sort -r /tmp/mptab | while read mp dev type opts; do
    if [ "x$mp" == "x/" ]; then
        echo "$dev $mp $type $opts 0 0" > $NEWROOT/etc/mtab
        mount -o remount,ro $NEWROOT/
    else
        if ! umount $NEWROOT/$mp; then
            mount -o remount,ro $NEWROOT/$mp
        fi
    fi
done

