#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -n "$WWDEVDISK" ]; then
    WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
fi

if [ -n "$WWROOTSIZE" ]; then
    WWROOTSIZE=4096
fi

if [ -n "$WWSWAPSIZE" ]; then
    WWSWAPSIZE=2048
fi


cat <<EOF | /sbin/fdisk /dev/$WWDEVDISK || exit 255
n
p
1

+${WWROOTSIZE}M
n
p
2

+${WWSWAPSIZE}M
t
2
82
w
EOF
