#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -z "$WWDEVDISK" ]; then
    WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
fi

BLOCKS=`cat /sys/class/block/$WWDEVDISK/size`
SIZE=`expr $BLOCKS / 2048`

if [ -z "$WWROOTSIZE" ]; then
    WWROOTSIZE=4096
fi

if [ -z "$WWSWAPSIZE" ]; then
    WWSWAPSIZE=2048
fi

TOTAL_SIZE=`expr $WWROOTSIZE + $WWSWAPSIZE + 64`

if [ $TOTAL_SIZE -gt $SIZE ]; then
    WWSWAPSIZE=`expr $SIZE / 8`
    WWROOTSIZE=`expr $SIZE - 64 - $WWSWAPSIZE`

fi

cat <<EOF | /sbin/fdisk /dev/$WWDEVDISK >/dev/null || exit 255
n
p
1

+${WWROOTSIZE}M
n
p
2

+${WWSWAPSIZE}M
t
2
82
w
EOF
