#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -z "$WWDEVDISK" ]; then
    WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
fi

if [ -z "$WWFILESYSTEM" ]; then
    WWFILESYSTEM=ext2
fi


if [ -x "/sbin/mkfs.$WWFILESYSTEM" ]; then
    if ! /sbin/mkfs.$WWFILESYSTEM /dev/${WWDEVDISK}1 >/dev/null ; then
        exit 255
    fi
fi
if ! /sbin/mkswap /dev/${WWDEVDISK}2 >/dev/null ; then
    exit 255
fi
