#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -z "$WWDEVDISK" ]; then
    WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
fi

if [ -z "$WWFILESYSTEM" ]; then
    WWFILESYSTEM=ext2
fi


cat <<EOF > $NEWROOT/etc/fstab
/dev/${WWDEVDISK}1 / $WWFILESYSTEM defaults 1 1
/dev/${WWDEVDISK}2 none swap defaults 0 0
EOF

cp /tmp/ifcfg-eth* $NEWROOT/etc/sysconfig/network-scripts/ 2>/dev/null
