#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -z "$WWDEVDISK" ]; then
    WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
fi

if [ -z "$WWFILESYSTEM" ]; then
    WWFILESYSTEM=ext2
fi

KERNELNAME=`cd $NEWROOT/boot; ls vmlinuz-* | tail -n 1`
INITRDNAME=`cd $NEWROOT/boot; ls initr* | tail -n 1`
KERNELVERSION=`echo $KERNELNAME | sed -e 's@.*vmlinuz-@@'`

if [ -f "$NEWROOT/etc/redhat-release" ]; then
    OSVERSION=`sed -e 's@ (.*@@' $NEWROOT/etc/redhat-release`
elif [ -f "$NEWROOT/etc/release" ]; then
    OSVERSION=`cat $NEWROOT/etc/redhat-release | head -n 1`
else
    OSVERSION="Warewulf"
fi

cat <<EOF > $NEWROOT/boot/grub/device.map
# This file was written by Warewulf bootstrap (capability provision-localdisk)
(hd0)     /dev/$WWDEVDISK
EOF

cat <<EOF > $NEWROOT/boot/grub/grub.conf
# This file was written by Warewulf bootstrap (capability provision-localdisk)
default 0
timeout 10
root (hd0,0)

title $OSVERSION - $KERNELVERSION
    kernel /boot/$KERNELNAME ro root=/dev/${WWDEVDISK}1 rhgb quiet
    initrd /boot/$INITRDNAME
EOF

cat <<EOF > $NEWROOT/etc/mtab
/dev/${WWDEVDISK}1 / $WWFILESYSTEM rw 0 0
EOF

# MAPPER HACK
mkdir $NEWROOT/dev/mapper
mknod $NEWROOT/dev/mapper/control c 10 58

chroot $NEWROOT /sbin/grub-install /dev/$WWDEVDISK >/dev/null

cat /dev/null > $NEWROOT/etc/mtab
