#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ "x$WWPOSTREBOOT" == "xyes" -a -f "/tmp/stateful-root" ]; then
    sort /tmp/filesystems | while read MOUNTPOINT DEV FILESYSTEM; do
        if [ -n "$MOUNTPOINT" ]; then
            echo "Unmounting $MOUNTPOINT"
            if ! umount $NEWROOT/$MOUNTPOINT; then
                mount -o remount,ro $NEWROOT/$MOUNTPOINT
            fi
        fi
    done

    echo
    echo
    echo "Rebooting in 5 seconds..."
    sync
    sleep 1
    sync
    sleep 1
    sync
    sleep 1
    sync
    sleep 1
    sync
    sleep 1
    sync
    /sbin/reboot -f
fi
