#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#


if [ -n "$WWTMPFSSIZE" ]; then
    OPTIONS="size=$WWTMPFSSIZE"
fi

if [ -n "$WWTMPFSOPTIONS" ]; then
    OPTIONS=",$WWTMPFSOPTIONS"
fi

if [ -n "$OPTIONS" ]; then
    OPTIONS="-o $OPTIONS"
fi


mkdir $NEWROOT
mount -t tmpfs $OPTIONS root $NEWROOT
